name: Prepare Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-minor-version:
    name: Bump Minor Version
    runs-on: ubuntu-latest
    if: !contains(github.event.head_commit.message, 'bump: version')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.HAWKY_APP_ID }}
          private_key: ${{ secrets.HAWKY_APP_PRIVATE_KEY }}
      - name: Set up git for pushing
        run: |
          git remote set-url origin https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/${{ github.repository }}.git
      - name: Set git user for HawkyMcBuilderFace bot
        run: |
          git config user.name "HawkyMcBuilderFace[bot]"
          git config user.email "hawkymcbuilderface[bot]@users.noreply.github.com"
      - name: Bump minor version with bumpver
        run: bumpver update --minor --commit
      - name: Push version bump commit
        run: |
          git push origin HEAD:main 