name: Prepare Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-minor-version:
    name: Bump Minor Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Set git user for github-actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Bump minor version with bumpver
        run: bumpver update --minor --commit
      - name: Push version bump commit
        run: |
          git push origin HEAD:main 