name: Publish Docker image

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
  release:
    types: [published]

jobs:
  build-and-push:
    if: >
      github.event_name == 'release' &&
      github.event.action == 'published' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stackhawk-mcp:latest,${{ secrets.DOCKERHUB_USERNAME }}/stackhawk-mcp:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64 